Metadata:
    Timestamp: 2013-08-02 18:27:21.269000
    Version:   1.0.0

BEGIN MESSAGE:

Top-level exception: Traceback (most recent call last):
  File "niftybot.py", line 134, in main
    user_interface.main()
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\user_interface.py", line 257, in main
    control = ControlPanel(robot, states)
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\user_interface.py", line 134, in __init__
    self.images.start('face')
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\sensor_analysis.py", line 274, in start
    img = self.cam.getImage().flipHorizontal()
  File "C:\Python27\lib\site-packages\SimpleCV\Camera.py", line 586, in getImage
    newimg = cv.CreateImage(cv.GetSize(frame), cv.IPL_DEPTH_8U, 3)
error: Array should be CvMat or IplImage

END MESSAGE

~~~~~~~~~~~~~~~~~~~~~~
Metadata:
    Timestamp: 2013-08-02 18:31:35.640000
    Version:   1.0.0

BEGIN MESSAGE:

Top-level exception: Traceback (most recent call last):
  File "niftybot.py", line 134, in main
    user_interface.main()
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\user_interface.py", line 258, in main
    control = ControlPanel(robot, states)
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\user_interface.py", line 134, in __init__
    self.images.start('face')
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\sensor_analysis.py", line 274, in start
    img = self.cam.getImage().flipHorizontal()
  File "C:\Python27\lib\site-packages\SimpleCV\Camera.py", line 586, in getImage
    newimg = cv.CreateImage(cv.GetSize(frame), cv.IPL_DEPTH_8U, 3)
error: Array should be CvMat or IplImage

END MESSAGE

~~~~~~~~~~~~~~~~~~~~~~
Metadata:
    Timestamp: 2013-08-12 08:12:02.797000
    Version:   1.0.0

BEGIN MESSAGE:

Top-level exception: Traceback (most recent call last):
  File ".\niftybot.py", line 134, in main
    user_interface.main()
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\user_interface.py", line 275, in main
    control = ControlPanel(robot, states)
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\user_interface.py", line 142, in __init__
    self.dashboard = dashboard.get_multiprocessing_app('dashboard', get_data)
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\dashboard.py", line 49, in get_multiprocessing_app
    return wrap_app_process(create_webapp(name, func_get_data))
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\dashboard.py", line 44, in wrap_app_process
    run = app.run
AttributeError: 'NoneType' object has no attribute 'run'

END MESSAGE

~~~~~~~~~~~~~~~~~~~~~~
Metadata:
    Timestamp: 2013-08-12 16:56:45.254000
    Version:   1.0.0

BEGIN MESSAGE:

Top-level exception: Traceback (most recent call last):
  File ".\niftybot.py", line 134, in main
    user_interface.main()
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\user_interface.py", line 280, in main
    control.mainloop()
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\user_interface.py", line 155, in mainloop
    self.setup()
  File "C:\Users\Michael\Dropbox\Projects\Code\Programs\Niftybot\Code\robot\user_interface.py", line 134, in setup
    self.cam = scv.Camera(0)
NameError: global name 'scv' is not defined

END MESSAGE

~~~~~~~~~~~~~~~~~~~~~~
